"""empty message

Revision ID: 38b9614345dd
Revises: 79ea45a118b7
Create Date: 2025-08-19 06:07:38.139787

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "38b9614345dd"
down_revision: Union[str, None] = "79ea45a118b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("network_addresses", "created_at")
    op.drop_column("network_addresses", "updated_at")
    op.drop_column("policy_terms", "created_at")
    op.drop_column("policy_terms", "updated_at")
    op.drop_column("service_entries", "created_at")
    op.drop_column("service_entries", "updated_at")
    op.drop_column("test_cases", "created_at")
    op.drop_column("test_cases", "updated_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("test_cases", sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column("test_cases", sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column(
        "service_entries", sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "service_entries", sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False)
    )
    op.add_column("policy_terms", sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column("policy_terms", sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column(
        "network_addresses", sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "network_addresses", sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
