"""empty message

Revision ID: 637c230c6d5c
Revises: b86cb4eaaa57
Create Date: 2025-03-29 10:23:26.762895

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = "637c230c6d5c"
down_revision: Union[str, None] = "b86cb4eaaa57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tests", sa.Column("comment", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tests", "comment")
    # ### end Alembic commands ###
