"""empty message

Revision ID: c81a0a490f7b
Revises: 4e2132d319b1
Create Date: 2025-05-03 10:46:00.876690

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = "c81a0a490f7b"
down_revision: Union[str, None] = "4e2132d319b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "policy_terms",
        "option",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum("ESTABLISHED", "IS-FRAGMENT", "TCP-ESTABLISHED", "TCP-INITIAL", name="policyoptionenum"),
        postgresql_using="option::policyoptionenum",
        existing_nullable=True,
    )
    op.alter_column(
        "policy_terms",
        "action",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum("ACCEPT", "DENY", "NEXT", "REJECT", "REJECT-WITH-TCP-RST", name="policyactionenum"),
        postgresql_using="action::policyactionenum",
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "policy_terms",
        "action",
        existing_type=sa.Enum("ACCEPT", "DENY", "NEXT", "REJECT", "REJECT-WITH-TCP-RST", name="policyactionenum"),
        type_=sa.VARCHAR(),
        nullable=True,
    )
    op.alter_column(
        "policy_terms",
        "option",
        existing_type=sa.Enum("ESTABLISHED", "IS-FRAGMENT", "TCP-ESTABLISHED", "TCP-INITIAL", name="policyoptionenum"),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
