"""empty message

Revision ID: a693a4930613
Revises: 42c7cafb7acb
Create Date: 2025-09-02 10:51:28.689998

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a693a4930613'
down_revision: Union[str, None] = '42c7cafb7acb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dynamic_policies', sa.Column('custom_aerleon_header', sa.String(), nullable=True))
    op.add_column('policies', sa.Column('custom_aerleon_header', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('policies', 'custom_aerleon_header')
    op.drop_column('dynamic_policies', 'custom_aerleon_header')
    # ### end Alembic commands ###
