"""empty message

Revision ID: 42c7cafb7acb
Revises: 38b9614345dd
Create Date: 2025-08-27 18:22:05.155826

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '42c7cafb7acb'
down_revision: Union[str, None] = '38b9614345dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dynamic_policies', sa.Column('edited', sa.Boolean(), nullable=False, default=False, server_default="False"))
    op.add_column('policies', sa.Column('edited', sa.Boolean(), nullable=False, default=False, server_default="False"))
    op.add_column('policy_terms', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('policy_terms', 'comment')
    op.drop_column('policies', 'edited')
    op.drop_column('dynamic_policies', 'edited')
    # ### end Alembic commands ###
