"""empty message

Revision ID: 4e2132d319b1
Revises: 637c230c6d5c
Create Date: 2025-05-02 09:14:53.765533

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = "4e2132d319b1"
down_revision: Union[str, None] = "637c230c6d5c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("deployer_git_configs", sa.Column("ssh_key_envvar", sa.String(), nullable=True))
    op.add_column("deployer_git_configs", sa.Column("auth_token_envvar", sa.String(), nullable=True))
    op.drop_column("deployer_git_configs", "ssh_key")
    op.drop_column("deployer_git_configs", "auth_token")
    op.add_column("deployer_netmiko_configs", sa.Column("username_envvar", sa.String(), nullable=False))
    op.add_column("deployer_netmiko_configs", sa.Column("password_envvar", sa.String(), nullable=True))
    op.add_column("deployer_netmiko_configs", sa.Column("enable_envvar", sa.String(), nullable=True))
    op.add_column("deployer_netmiko_configs", sa.Column("ssh_key_envvar", sa.String(), nullable=True))
    op.drop_column("deployer_netmiko_configs", "enable")
    op.drop_column("deployer_netmiko_configs", "password")
    op.drop_column("deployer_netmiko_configs", "username")
    op.drop_column("deployer_netmiko_configs", "ssh_key")
    op.add_column("deployer_proxmox_nft_configs", sa.Column("username_envvar", sa.String(), nullable=False))
    op.add_column("deployer_proxmox_nft_configs", sa.Column("password_envvar", sa.String(), nullable=True))
    op.add_column("deployer_proxmox_nft_configs", sa.Column("ssh_key_envvar", sa.String(), nullable=True))
    op.drop_column("deployer_proxmox_nft_configs", "password")
    op.drop_column("deployer_proxmox_nft_configs", "username")
    op.drop_column("deployer_proxmox_nft_configs", "ssh_key")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "deployer_proxmox_nft_configs", sa.Column("ssh_key", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "deployer_proxmox_nft_configs", sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "deployer_proxmox_nft_configs", sa.Column("password", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_column("deployer_proxmox_nft_configs", "ssh_key_envvar")
    op.drop_column("deployer_proxmox_nft_configs", "password_envvar")
    op.drop_column("deployer_proxmox_nft_configs", "username_envvar")
    op.add_column("deployer_netmiko_configs", sa.Column("ssh_key", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column("deployer_netmiko_configs", sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column("deployer_netmiko_configs", sa.Column("password", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column("deployer_netmiko_configs", sa.Column("enable", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column("deployer_netmiko_configs", "ssh_key_envvar")
    op.drop_column("deployer_netmiko_configs", "enable_envvar")
    op.drop_column("deployer_netmiko_configs", "password_envvar")
    op.drop_column("deployer_netmiko_configs", "username_envvar")
    op.add_column("deployer_git_configs", sa.Column("auth_token", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column("deployer_git_configs", sa.Column("ssh_key", sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column("deployer_git_configs", "auth_token_envvar")
    op.drop_column("deployer_git_configs", "ssh_key_envvar")
    # ### end Alembic commands ###
