"""empty message

Revision ID: 15a8b0d9740f
Revises: c81a0a490f7b
Create Date: 2025-05-03 10:53:29.314295

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = "15a8b0d9740f"
down_revision: Union[str, None] = "c81a0a490f7b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE IF EXISTS dynamicpolicyfilteractionenum CASCADE")
    dynamic_policy_filter_action_enum = sa.Enum(
        "ACCEPT", "DENY", "NEXT", "REJECT", "REJECT-WITH-TCP-RST", name="dynamicpolicyfilteractionenum"
    )
    # 1. Create the ENUM type in PostgreSQL
    dynamic_policy_filter_action_enum.create(op.get_bind(), checkfirst=True)

    op.alter_column(
        "dynamic_policies",
        "filter_action",
        existing_type=sa.VARCHAR(),
        type_=dynamic_policy_filter_action_enum,
        postgresql_using="filter_action::dynamicpolicyfilteractionenum",
        existing_nullable=True,
    )

    op.execute("DROP TYPE IF EXISTS dynamicpolicydefaultactionenum CASCADE")
    dynamic_policy_default_action_enum = sa.Enum(
        "ACCEPT", "ACCEPT_LOG", "DENY", "DENY_LOG", name="dynamicpolicydefaultactionenum"
    )
    # 1. Create the ENUM type in PostgreSQL
    dynamic_policy_default_action_enum.create(op.get_bind(), checkfirst=True)

    op.alter_column(
        "dynamic_policies",
        "default_action",
        existing_type=sa.VARCHAR(),
        type_=dynamic_policy_default_action_enum,
        postgresql_using="default_action::dynamicpolicydefaultactionenum",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dynamic_policies",
        "default_action",
        existing_type=sa.Enum("ACCEPT", "ACCEPT_LOG", "DENY", "DENY_LOG", name="dynamicpolicydefaultactionenum"),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "dynamic_policies",
        "filter_action",
        existing_type=sa.Enum(
            "accept", "deny", "next", "reject", "reject_with_tcp_rst", name="dynamicpolicyfilteractionenum"
        ),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
