"""empty message

Revision ID: f345a19b7447
Revises: a693a4930613
Create Date: 2025-09-02 17:11:05.754125

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = "f345a19b7447"
down_revision: Union[str, None] = "a693a4930613"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("target_replacements", "target_substitutions")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("target_substitutions", "target_replacements")
    # ### end Alembic commands ###
