"""empty message

Revision ID: c825fa8e8ee7
Revises: 15a8b0d9740f
Create Date: 2025-05-06 17:34:15.678285

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c825fa8e8ee7"
down_revision: Union[str, None] = "15a8b0d9740f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "policy_terms",
        "action",
        existing_type=postgresql.ENUM(
            "ACCEPT", "DENY", "NEXT", "REJECT", "REJECT_WITH_TCP_RST", name="policyactionenum"
        ),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "policy_terms",
        "action",
        existing_type=postgresql.ENUM(
            "ACCEPT", "DENY", "NEXT", "REJECT", "REJECT_WITH_TCP_RST", name="policyactionenum"
        ),
        nullable=False,
    )
    # ### end Alembic commands ###
